# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 17:24
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amb_time', models.DateTimeField(auto_now_add=True)),
                ('area', models.CharField(blank=True, default=False, max_length=50)),
                ('city', models.CharField(blank=True, default=False, max_length=50)),
                ('phone', models.CharField(blank=True, default=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_telno', models.CharField(blank=True, default=False, max_length=20)),
                ('our_telno', models.CharField(blank=True, default=False, max_length=20)),
                ('doctor', models.CharField(blank=True, default=False, max_length=50)),
                ('patient', models.CharField(blank=True, default=False, max_length=50)),
                ('pay_time', models.DateTimeField(auto_now_add=True)),
                ('cons_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telno', models.CharField(blank=True, default=False, max_length=20)),
                ('email', models.CharField(blank=True, default=False, max_length=50)),
                ('msg', models.CharField(default=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=40)),
                ('pname', models.CharField(max_length=50)),
                ('sname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=30)),
                ('illness', models.CharField(max_length=700)),
                ('comp_signs', models.CharField(max_length=700)),
                ('kin', models.CharField(max_length=30)),
                ('kintelno', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('page', models.IntegerField()),
                ('amb', models.CharField(default=False, max_length=5)),
                ('amt', models.CharField(default=False, max_length=5)),
                ('doctorusername', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=700)),
                ('when', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('dtelno', models.CharField(blank=True, max_length=20)),
                ('dname', models.CharField(max_length=40)),
                ('demail', models.CharField(max_length=40)),
                ('consultation_success', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Labtests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telno', models.CharField(blank=True, default=False, max_length=20)),
                ('area', models.CharField(blank=True, default=False, max_length=50)),
                ('city', models.CharField(blank=True, default=False, max_length=50)),
                ('msg', models.CharField(default=False, max_length=20)),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('staff_no', models.CharField(blank=True, default=False, max_length=70)),
                ('staff_name', models.CharField(blank=True, default=False, max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b's', b'system'), (b'a', b'action'), (b'm', b'message'), (b'j', b'join'), (b'l', b'leave'), (b'n', b'notification')], max_length=1)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orderdrugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telno', models.CharField(blank=True, default=False, max_length=20)),
                ('area', models.CharField(blank=True, default=False, max_length=50)),
                ('city', models.CharField(blank=True, default=False, max_length=50)),
                ('msg', models.CharField(default=False, max_length=20)),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('staff_no', models.CharField(blank=True, default=False, max_length=70)),
                ('staff_name', models.CharField(blank=True, default=False, max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, default=False, max_length=20)),
                ('sname', models.CharField(blank=True, default=False, max_length=30)),
                ('page', models.IntegerField(blank=True)),
                ('gender', models.CharField(blank=True, default=False, max_length=30)),
                ('telno', models.CharField(blank=True, default=False, max_length=20)),
                ('username', models.CharField(blank=True, default=False, max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(blank=True, default=False, max_length=50)),
                ('street', models.CharField(blank=True, default=False, max_length=50)),
                ('city', models.CharField(blank=True, default=False, max_length=20)),
                ('state', models.CharField(blank=True, default=False, max_length=20)),
                ('role2', models.CharField(default=False, max_length=20)),
                ('specialty', models.CharField(default=False, max_length=20)),
                ('access_right', models.CharField(default=False, max_length=30)),
                ('account_blocked', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, default=False, max_length=50)),
                ('dUsername', models.CharField(blank=True, default=False, max_length=50)),
                ('dtelno', models.CharField(default=False, max_length=50, null=True)),
                ('payment', models.CharField(default=False, max_length=50, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Room'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set([('content_type', 'object_id')]),
        ),
    ]
