# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, default=False, max_length=20)),
                ('sname', models.CharField(blank=True, default=False, max_length=30)),
                ('page', models.IntegerField(blank=True)),
                ('gender', models.CharField(blank=True, default=False, max_length=30)),
                ('telno', models.CharField(blank=True, default=False, max_length=20)),
                ('username', models.CharField(blank=True, default=False, max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('email', models.CharField(blank=True, default=False, max_length=50)),
                ('street', models.CharField(blank=True, default=False, max_length=50)),
                ('city', models.CharField(blank=True, default=False, max_length=20)),
                ('state', models.CharField(blank=True, default=False, max_length=20)),
                ('zip_code', models.CharField(blank=True, default=False, max_length=5)),
                ('specialty', models.CharField(default=False, max_length=20)),
                ('role', models.CharField(default=False, max_length=20)),
                ('account_blocked', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('staff_only', models.BooleanField(default=False)),
            ],
        ),
    ]
