# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='role',
        ),
        migrations.AddField(
            model_name='register',
            name='access_right',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='room',
            name='access_right',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='d_username',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='p_username',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
