# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-17 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdrugs',
            name='total',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
