# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_register_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='zip_code',
            field=models.CharField(blank=True, default=False, max_length=20),
        ),
    ]
