# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20170629_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='zip_code',
            new_name='zipcode',
        ),
    ]
