# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-30 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_register_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='zipcode',
            new_name='zipcode2',
        ),
    ]
