# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20170630_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='zipcodes',
            new_name='zipcodes2',
        ),
    ]
