# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20170701_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='zipcodes2',
            new_name='roles2',
        ),
    ]
