# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-08 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20170702_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='roles2',
            new_name='role2',
        ),
    ]
