# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-08 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20170708_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='role2',
            new_name='roles2',
        ),
    ]
