# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-09 10:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20170708_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('email', models.CharField(max_length=40)),
                ('pname', models.CharField(max_length=50)),
                ('sname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=30)),
                ('illness', models.CharField(max_length=700)),
                ('comp_signs', models.CharField(max_length=700)),
                ('kin', models.CharField(max_length=30)),
                ('kintelno', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('page', models.IntegerField()),
                ('amb', models.CharField(default=False, max_length=5)),
                ('amt', models.CharField(default=False, max_length=5)),
                ('doctorusername', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=700)),
                ('when', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('dtelno', models.CharField(max_length=20)),
                ('dname', models.CharField(max_length=40)),
                ('demail', models.CharField(max_length=40)),
                ('consultation_success', models.BooleanField(default=False)),
            ],
        ),
    ]
