# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-09 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_illness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illness',
            name='dtelno',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
