# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 06:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0016_auto_20170709_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b's', b'system'), (b'a', b'action'), (b'm', b'message'), (b'j', b'join'), (b'l', b'leave'), (b'n', b'notification')], max_length=1)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='room',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='createdBy',
            field=models.CharField(blank=True, default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='dUsername',
            field=models.CharField(blank=True, default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='illness',
            name='added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='room',
            name='access_right',
        ),
        migrations.RemoveField(
            model_name='room',
            name='d_username',
        ),
        migrations.RemoveField(
            model_name='room',
            name='p_username',
        ),
        migrations.RemoveField(
            model_name='room',
            name='staff_only',
        ),
        migrations.RemoveField(
            model_name='room',
            name='title',
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set([('content_type', 'object_id')]),
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Room'),
        ),
    ]
