# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_auto_20170806_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='dtelno',
            field=models.CharField(blank=True, default=False, max_length=50),
        ),
    ]
