# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_room_dtelno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='dtelno',
            field=models.CharField(default=False, max_length=50, null=True),
        ),
    ]
