# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_auto_20171014_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amb_time', models.DateTimeField(auto_now_add=True)),
                ('area', models.CharField(blank=True, default=False, max_length=50)),
                ('city', models.CharField(blank=True, default=False, max_length=50)),
                ('phone', models.CharField(blank=True, default=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Labtests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telno', models.CharField(blank=True, default=False, max_length=20)),
                ('area', models.CharField(blank=True, default=False, max_length=50)),
                ('city', models.CharField(blank=True, default=False, max_length=50)),
                ('msg', models.CharField(default=False, max_length=20)),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('staff_no', models.CharField(blank=True, default=False, max_length=70)),
                ('staff_name', models.CharField(blank=True, default=False, max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Orderdrugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telno', models.CharField(blank=True, default=False, max_length=20)),
                ('area', models.CharField(blank=True, default=False, max_length=50)),
                ('city', models.CharField(blank=True, default=False, max_length=50)),
                ('msg', models.CharField(default=False, max_length=20)),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('staff_no', models.CharField(blank=True, default=False, max_length=70)),
                ('staff_name', models.CharField(blank=True, default=False, max_length=70)),
            ],
        ),
    ]
